### SERVER ###
# frps.toml

# INFORMAÇÕES DO SERVIDOR
auth.method = "token"
auth.token = "{{ .Envs.SECURITY_PASS }}"
bindAddr = "0.0.0.0"
bindPort = 998

kcpBindPort = 998
quicBindPort = 997
proxyBindAddr = "0.0.0.0"

# TEMPO EM SEGUNDOS PARA CHECAR A CONEXÃO
transport.tcpKeepalive = 10

# MÁXIMO DE CONEXÕES ABERTAS (POR CLIENTE)
transport.maxPoolCount = 50

# LOGS
# log.to = "z_OUTROS/z_logs-frps.txt"
# log.level = "info"
# log.maxDays = 3

# DASHBOARD WEB (NAO ALTERAR NADA!!!)
webServer.user = "Administrator"
webServer.password = "{{ .Envs.SECURITY_PASS }}"
webServer.addr = "0.0.0.0"
webServer.port = 999
