### CLIENT ### *** type | "xtcp" → P2P (passa pelo servidor: NÃO) | "tcp" → (passa pelo servidor: SIM) expor na web | "stcp" → (passa pelo servidor: SIM) relay [só funciona localmente e precisa do frpc na origem e destino]
# frpc.toml {0} → FLY_IO (apenas para expor na WEB via P2P) - {1} → HP - {2} → ESTRELAR - {3} → OPSEUA - {4} → MARCOS - {5} → THAYNA

# DESTINO E CONEXÃO
serverAddr = "127.0.0.1"
auth.method = "token"
auth.token = "{{ .Envs.confSecurityPass }}"
serverPort = 997 # 997 (QUIC) | 998 (TCP)
transport.protocol = "quic" # quic | tcp
transport.tls.enable = true

# natHoleStunServer = "127.0.0.1:3478"
transport.dialServerKeepalive = 10 # TEMPO EM SEGUNDOS PARA CHECAR A CONEXÃO
transport.poolCount = 50 # MÁXIMO DE CONEXÕES ABERTAS

# DASHBOARD E LOGS
webServer.addr = "0.0.0.0"
webServer.user = "Administrator"
webServer.password = "{{ .Envs.confSecurityPass }}"
webServer.port = 9999
# log.to = "z_OUTROS/z_logs-frpc.txt"
log.level = "info"
log.maxDays = 3

# NOME CLIENTE
user = "0-FLY_IO"

# ############################################# SERVIÇOS: CONECTAR → http://127.0.0.1:x384 (SEMPRE bindAddr = "0.0.0.0")

[[visitors]]
name = "1-VIS-frp"
type = "xtcp"
serverUser = "1-HP"
serverName = "1-LOC-frp"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 1999

[[visitors]]
name = "1-VIS-Syncthing"
type = "xtcp"
serverUser = "1-HP"
serverName = "1-LOC-Syncthing"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 1384

# ---

[[visitors]]
name = "3-VIS-frp"
type = "xtcp"
serverUser = "3-OPSEUA"
serverName = "3-LOC-frp"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 3999

[[visitors]]
name = "3-VIS-Syncthing"
type = "xtcp"
serverUser = "3-OPSEUA"
serverName = "3-LOC-Syncthing"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 3384

[[visitors]]
name = "3-VIS-Files"
type = "xtcp"
serverUser = "3-OPSEUA"
serverName = "3-LOC-Files"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 3445

# ---

[[visitors]]
name = "4-VIS-frp"
type = "xtcp"
serverUser = "4-MARCOS"
serverName = "4-LOC-frp"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 4999

[[visitors]]
name = "4-VIS-Syncthing"
type = "xtcp"
serverUser = "4-MARCOS"
serverName = "4-LOC-Syncthing"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 4384

[[visitors]]
name = "4-VIS-Screen"
type = "xtcp"
serverUser = "4-MARCOS"
serverName = "4-LOC-Screen"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 4777

# ---

[[visitors]]
name = "5-VIS-Server"
type = "xtcp"
serverUser = "5-LINUX"
serverName = "5-LOC-Server"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 3000

# ---
