### CLIENT ### *** type | "xtcp" → P2P (passa pelo servidor: NÃO) | "tcp" → (passa pelo servidor: SIM) expor na web | "stcp" → (passa pelo servidor: SIM) relay [só funciona localmente e precisa do frpc na origem e destino]
# frpc.toml {0} → FLY_IO (apenas para expor na WEB via P2P) - {1} → HP - {2} → ESTRELAR - {3} → OPSEUA - {4} → MARCOS - {5} → THAYNA

# DESTINO E CONEXÃO
serverAddr = "127.0.0.1"
auth.method = "token"
auth.token = "{{ .Envs.confSecurityPass }}"
serverPort = 997 # 997 (QUIC) | 998 (TCP)
transport.protocol = "quic" # quic | tcp
transport.tls.enable = true

# natHoleStunServer = "stunserver2025.stunprotocol.org:3478"
transport.dialServerKeepalive = 10 # TEMPO EM SEGUNDOS PARA CHECAR A CONEXÃO
transport.poolCount = 50 # MÁXIMO DE CONEXÕES ABERTAS

# DASHBOARD E LOGS
webServer.addr = "0.0.0.0"
webServer.user = "Administrator"
webServer.password = "{{ .Envs.confSecurityPass }}"
webServer.port = 9999
# log.to = "z_OUTROS/z_logs-frpc.txt"
log.level = "info"
log.maxDays = 3

# NOME CLIENTE
user = "0-FLY_IO"

# ############################################# SERVIÇOS: CONECTAR → http://127.0.0.1:x384

[[visitors]]
name = "1-VIS-frp"
type = "xtcp"
serverUser = "1-HP"
serverName = "1-LOC-frp"
secretKey = "{{ .Envs.confSecurityPass }}"
bindAddr = "0.0.0.0"
bindPort = 5999
