### SERVER ###
# frps.toml

# DESTINO E CONEXÃO
proxyBindAddr = "0.0.0.0"
bindAddr = "0.0.0.0"
auth.method = "token"
auth.token = "{{ .Envs.confSecurityPass }}"
bindPort = 998
# quicBindPort = 998 # (QUIC)

transport.heartbeatTimeout = 15 # CHECAGEM DE PING
transport.maxPoolCount = 50 # CONEXÕES ABERTAS SIMULTANEAMENTE (POR CLIENTE)

# DASHBOARD E LOGS
webServer.addr = "0.0.0.0"
webServer.user = "Administrator"
webServer.password = "{{ .Envs.confSecurityPass }}"
webServer.port = 9999
# log.to = "z_OUTROS/z_logs-frps.txt"
log.level = "warn" # trace, debug, info, warn, error
log.maxDays = 3
