app = "opseua-deploy"
primary_region = "gru"

[build]

# frps túnel - TCP puro
[[services]]
internal_port = 7000
protocol = "tcp"
[[services.ports]]
port = 7000

# frps dashboard
[[services]]
internal_port = 7500
protocol = "tcp"
[[services.ports]]
port = 7500
handlers = ["http"]

# nats websocket
[[services]]
internal_port = 8080
protocol = "tcp"
[[services.ports]]
port = 80
handlers = ["http"]
[[services.ports]]
port = 443
handlers = ["tls", "http"]

# bridge comunicação (HTTP + WebSocket)
[[services]]
internal_port = 9877
protocol = "tcp"
[[services.ports]]
port = 9877
handlers = ["http"]

# versionamento
[[services]]
internal_port = 3000
protocol = "tcp"
[[services.ports]]
port = 3000
handlers = ["http"]

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
