app = "opseua-deploy"
primary_region = "gru"

[build]

# frps (túnel reverso)
[[services]]
internal_port = 7000
protocol = "tcp"
[[services.ports]]
port = 7000

# frps web dashboard
[[services]]
internal_port = 7500
protocol = "tcp"
[[services.ports]]
port = 7500

# servidor de comunicação (WebSocket)
[[services]]
internal_port = 8080
protocol = "tcp"
[[services.ports]]
port = 80
handlers = ["http"]
[[services.ports]]
port = 443
handlers = ["tls", "http"]

# servidor de versionamento
[[services]]
internal_port = 3000
protocol = "tcp"
[[services.ports]]
port = 3000

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
