name: Deploy to Fly.io

on:
  push:
    branches: [main]
    paths:
      - 'communication/**'
      - 'frps/**'
      - 'version/**'
      - 'main.js'
      - 'Dockerfile'
      - 'fly.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar início
        run: curl -s "https://ntfy.sh/${{ secrets.NTFY_CHANNEL }}/publish?title=GitHub+Action&message=Deploy+em+andamento"

      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}